name: wasm-artifacts

on:
    push:
        paths:
            - "**/*.rs"
            - "Cargo.toml"
            - "Cargo.lock"
            - "pkg/**"
            - "xtask/**"
    pull_request:
        paths:
            - "**/*.rs"
            - "Cargo.toml"
            - "Cargo.lock"
            - "pkg/**"
            - "xtask/**"

jobs:
    verify-wasm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Rust
              uses: dtolnay/rust-toolchain@master
              with:
                  toolchain: "1.81.0"
            - name: Install wasm-pack
              run: cargo install wasm-pack --locked --version 0.12.1
            - name: Check committed WASM artifacts
              run: cargo xtask wasm check
